<?php
class GamblingSimulation                //Class declaration
{
    //Declaring Constants
    const BET=1;
    const STAKE=100;
    const NO_OF_DAYS=20;

    //Created method for displaying welcome message
    function welcome_mesage()
    {
        echo "=======================================\n";
        echo "Welcome to Gambling Simulation Program\n";
        echo "=======================================\n";
    }


    //Method to check win or lose by using random function
    function win_or_loss()
    {
        $win=1;
        $random_check=rand(0,1);        //Getting 1 or 2 by using rand() function

        //Checking the value generated by random is equals to win or not.. if yes.. outputs 'Win' else 'Loss'
        if($random_check==$win)
        {
            echo "Win ! \n";
        }
        else
        {
            echo "Loss ! \n";
        }
    }

    //Methos to check win or loss after 50%
    function resign_game()
    {
        //Declaring variables
        $cash = self::STAKE;
        $win=1;
        $end=150;
        $start=50;
        $range=50;
        $no_of_win=0;
        $no_of_lose=0;

        //Checking cash is greater than start and less than end or not
        while( $cash < $end && $cash > $start)
        {
            if($win==$range)
            {
                $cash+=self::BET;       // if win matches to the range then cash will be incremented
            }
            else
            {
                $cash-=self::BET;       // if win not matches to the range then cash will be decremented
            }
        }
        //Checking if collected cash is gerater than start cash then win or else loss
        if($cash>=$start)
        {
            $no_of_win++;
            echo "Win \n";
        }
        else
        {
            $no_of_lose--;
            echo "Loss \n";
        }
    }

    //Method for win amount for 20 days
    function no_of_days()
    {
        $win=0;
        $win_amount=0;
        //Loop for number of days
        for($day=1; $day < self::NO_OF_DAYS; $day++)
        {

            //Calculating win amount for number of days
            while($day < self::NO_OF_DAYS)
            {
                $win_amount+=self::STAKE;
                $day++;
            }
            echo $win_amount;
        }
    }
    
}

//Creating Objects
$gambling_simulator_object=new GamblingSimulation();
//Caling  Methods
$gambling_simulator_object->welcome_mesage();
$gambling_simulator_object->win_or_loss();
$gambling_simulator_object->resign_game();
$gambling_simulator_object->no_of_days();

?>