<?php
class GamblingSimulation                //Class declaration
{
    //Declaring Constants
    const BET=1;
    const STAKE=100;
    const NO_OF_DAYS=20;

    //Created method for displaying welcome message
    function welcome_mesage()
    {
        echo "=======================================\n";
        echo "Welcome to Gambling Simulation Program\n";
        echo "=======================================\n";
    }


    //Method to check win or lose by using random function
    function win_or_loss()
    {
        $win=1;
        $random_check=rand(0,1);        //Getting 1 or 2 by using rand() function

        //Checking the value generated by random is equals to win or not.. if yes.. outputs 'Win' else 'Loss'
        if($random_check==$win)
        {
            echo "Win ! \n";
        }
        else
        {
            echo "Loss ! \n";
        }
    }

    
    
}

//Creating Object
$gambling_simulator_object=new GamblingSimulation();
//Calling Methods
$gambling_simulator_object->welcome_mesage();
$gambling_simulator_object->win_or_loss();

?>